
server:
  port: 9025
  
  
spring:
  datasource:
    url: jdbc:postgresql://robsqldatabase-1.c7wku7bns1td.us-west-1.rds.amazonaws.com:5432/yawpdb
    username: yawp
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update